batch_size: 4
d_lr_mult: 2.0
d_reg_every: 16
dataset_path: /workspace/liveavatar_data/renderer_dataset
depth: 2
display_freq: 1000
drop_path: 0.1
exp_name: custom_renderer_v2
exp_path: ./exps
gan_weight: 1.0
iter: 10000
latent_dim: 32
loss_dist: 1.0
loss_l1: 1.0
loss_vgg_all: 10.0
loss_vgg_face: 50.0
low_res_depth: 2
lr: 5.0e-06
n_disc: 2
num_heads: 8
r1_weight: 10.0
resume_ckpt: /workspace/exps/custom_renderer/checkpoints/step=010000.ckpt
save_freq: 1000
swin_res_threshold: 128
window_size: 8
